name: Ready the code and deploy

on: [push, workflow_dispatch]

jobs: 
  test-code:
    runs-on: ubuntu-latest

    steps:
      - name: Print a working directory
        run: |
            node -v
            git --version

      - name: Check Linting
        run: echo "Linting checking..."
    
